---
- name: Setup local environment
  hosts: localhost
  vars:
    supported_os:
      - Darwin # macOS
      - Debian # Ubuntu, Debian
    nsfw_mode: "{{ lookup('env', 'OJ39_ANSIBLE_INSTALL_NSFW') | default(false) | bool }}"
    is_ci: "{{ lookup('env', 'OJ39_ANSIBLE_IS_CI') | default(false) | bool }}"

  tasks:
    - name: (Setup) Check if OS is supported
      ansible.builtin.assert:
        that: ansible_facts['os_family'] in supported_os
        fail_msg: "Unsupported OS: {{ ansible_facts['os_family'] }}"

    - name: (Setup) Output NSFW Mode
      ansible.builtin.debug:
        var: nsfw_mode

    - name: (Setup) Output CI Mode
      ansible.builtin.debug:
        var: is_ci

    - name: (Setup) Include OS-specific vars
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "vars/{{ ansible_facts['os_family'] | lower }}/*.yml"

    - name: (Setup) Include common vars
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "vars/common/*.yml"

    - name: (Setup) Include OS-specific tasks
      ansible.builtin.include_tasks: "{{ item }}"
      with_fileglob:
        - "tasks/{{ ansible_facts['os_family'] | lower }}/*.yml"

    - name: (Setup) Include common tasks
      ansible.builtin.include_tasks: "{{ item }}"
      with_fileglob:
        - "tasks/common/*.yml"

  # handlers:
  #   - import_tasks: handlers/*.yml
