---
- name: Setup development environment
  hosts: localhost
  vars:
    supported_os:
      - Darwin # macOS
      - Debian # Ubuntu, Debian

  tasks:
    - name: Check if OS is supported
      assert:
        that: ansible_facts['os_family'] in supported_os
        fail_msg: "Unsupported OS: {{ ansible_facts['os_family'] }}"

    - name: Include OS-specific vars
      include_vars: "{{ item }}"
      with_fileglob:
        - "vars/{{ ansible_facts['os_family'] | lower }}/*.yml"

    - name: Include common vars
      include_vars: "{{ item }}"
      with_fileglob:
        - "vars/common/*.yml"

    - name: Include OS-specific tasks
      include_tasks: "{{ item }}"
      with_fileglob:
        - "tasks/{{ ansible_facts['os_family'] | lower }}/*.yml"

    - name: Include common tasks
      include_tasks: "{{ item }}"
      with_fileglob:
        - "tasks/common/*.yml"

  # handlers:
  #   - import_tasks: handlers/*.yml
