---
- name: Brew packages
  tags: brew_packages
  block:
    - name: (Brew) Install Brew packages
      community.general.homebrew:
        name: "{{ b_p_item }}"
        state: present
      loop: "{{ brew_packages }}"
      loop_control:
        loop_var: b_p_item
        label: "{{ b_p_item }}"

    - name: (Brew)Install Not-for-Work Brew packages
      community.general.homebrew:
        name: "{{ b_nfw_p_item }}"
        state: present
      loop: "{{ nfw_brew_packages }}"
      loop_control:
        loop_var: b_nfw_p_item
        label: "{{ b_nfw_p_item }}"
      when: work_mode | bool

    - name: (Brew)Install Brew casks
      community.general.homebrew:
        name: "{{ b_c_item }}"
        state: present
      loop: "{{ brew_casks }}"
      loop_control:
        loop_var: b_c_item
        label: "{{ b_c_item }}"

    - name: (Brew)Install Not-for-Work Brew casks
      community.general.homebrew:
        name: "{{ b_nfw_c_item }}"
        state: present
      loop: "{{ nfw_brew_casks }}"
      loop_control:
        loop_var: b_nfw_c_item
        label: "{{ b_nfw_c_item }}"
      when: work_mode | bool
