---
- name: Check if Homebrew is installed
  ansible.builtin.command: which brew
  register: homebrew_check
  ignore_errors: true
  changed_when: false

# TODO: NOt working
- name: Install Homebrew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  when: homebrew_check.rc != 0

- name: Install Brew packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: present
