---
- name: Install SFW Brew packages
  community.general.homebrew:
    name: "{{ b_sfw_p_item }}"
    state: present
  loop: "{{ sfw_brew_packages }}"
  loop_control:
    loop_var: b_sfw_p_item
    label: "{{ b_sfw_p_item }}"

- name: Install NSFW Brew packages
  community.general.homebrew:
    name: "{{ b_nsfw_p_item }}"
    state: present
  loop: "{{ nsfw_brew_packages }}"
  loop_control:
    loop_var: b_nsfw_p_item
    label: "{{ b_nsfw_p_item }}"
  when: nsfw_mode | bool

- name: Install SFW Brew casks
  community.general.homebrew:
    name: "{{ b_sfw_c_item }}"
    state: present
  loop: "{{ sfw_brew_casks }}"
  loop_control:
    loop_var: b_sfw_c_item
    label: "{{ b_sfw_c_item }}"

- name: Install NSFW Brew casks
  community.general.homebrew:
    name: "{{ b_nsfw_c_item }}"
    state: present
  loop: "{{ nsfw_brew_casks }}"
  loop_control:
    loop_var: b_nsfw_c_item
    label: "{{ b_nsfw_c_item }}"
  when: nsfw_mode | bool
