---
- name: Brew packages
  tags: brew_packages
  when: not ansible_check_mode
  block:
    - name: (Brew) Install Brew packages
      community.general.homebrew:
        name: "{{ b_p_item }}"
        state: present
      loop: "{{ brew_packages }}"
      loop_control:
        loop_var: b_p_item
        label: "{{ b_p_item }}"

    - name: (Brew)Install personal Brew packages
      community.general.homebrew:
        name: "{{ b_pers_p_item }}"
        state: present
      loop: "{{ pers_brew_packages }}"
      loop_control:
        loop_var: b_pers_p_item
        label: "{{ b_pers_p_item }}"
      when: mode == 'personal'

    - name: (Brew)Install Brew casks
      community.general.homebrew:
        name: "{{ b_c_item }}"
        state: present
      loop: "{{ brew_casks }}"
      loop_control:
        loop_var: b_c_item
        label: "{{ b_c_item }}"

    - name: (Brew)Install personal Brew casks
      community.general.homebrew:
        name: "{{ b_pers_c_item }}"
        state: present
      loop: "{{ pers_brew_casks }}"
      loop_control:
        loop_var: b_pers_c_item
        label: "{{ b_pers_c_item }}"
      when: mode == 'personal'
