- name: Setup iTerm2
  tags: iTerm2
  vars:
    zsh_custom: "{{ lookup('env', 'ZSH_CUSTOM') }}"
  block:
    - name: Synchronize font files
      ansible.posix.synchronize:
        src: "files/common/fonts/"
        dest: "~/Library/Fonts/"

    - name: Synchronize iTerm2 configuration
      ansible.posix.synchronize:
        src: "files/darwin/iterm2/com.googlecode.iterm2.plist"
        dest: "~/Library/Preferences/com.googlecode.iterm2.plist"
