- name: Setup iTerm2
  tags: iTerm2
  vars:
    zsh_custom: "{{ lookup('env', 'ZSH_CUSTOM') }}"
  block:
    - name: (iTerm2) Get current working directory
      ansible.builtin.command: pwd
      register: pwd

    - name: (iTerm2) Synchronize font files
      ansible.posix.synchronize:
        src: "{{ '/tmp/oj39/universal-setup/files/common/fonts/' if pwd.stdout == '/tmp/oj39/universal-setup-work-extension' else 'files/common/fonts/' }}"
        dest: "~/Library/Fonts/"

    - name: (iTerm2) Synchronize iTerm2 configuration
      ansible.posix.synchronize:
        src: "{{ '/tmp/oj39/universal-setup/files/darwin/iterm2/com.googlecode.iterm2.plist' if pwd.stdout == '/tmp/oj39/universal-setup-work-extension' else 'files/darwin/iterm2/com.googlecode.iterm2.plist' }}"
        src: "files/darwin/iterm2/com.googlecode.iterm2.plist"
        dest: "~/Library/Preferences/com.googlecode.iterm2.plist"
