- name: Setup Zsh
  tags: zsh
  block:
    - name: Create .zshrc in home for Darwin
      ansible.legacy.file:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: touch
        mode: "0644"
      when: ansible_os_family == "Darwin" and is_ci | bool

    - name: Ensure lines are present in .zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        regexp: "^{{ zshrc_lines_item.split('=')[0] }}="
        line: "{{ zshrc_lines_item }}"
      loop: "{{ zshrc_lines }}"
      loop_control:
        loop_var: zshrc_lines_item
      become: true
      when: ansible_os_family == "Darwin"

    - name: Ensure lines are absent in .zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        regexp: "^{{ remove_zshrc_lines_item.split('=')[0] }}="
        state: absent
      loop: "{{ remove_zshrc_lines }}"
      loop_control:
        loop_var: remove_zshrc_lines_item
      become: true
      when: ansible_os_family == "Darwin" and remove_zshrc_lines_item is defined

    - name: Ensure block present in .zshrc
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        block: "{{ rc_block }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - RC BLOCK"
      become: true
      when: ansible_os_family == "Darwin"

    - name: Ensure OS specific block present in .zshrc
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        block: "{{ rc_block_zsh }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - RC BLOCK ZSH"
      become: true
      when: ansible_os_family == "Darwin"

    ## CI DEBUG
    - name: Show contents of .zshrc in CI
      ansible.builtin.command: cat "{{ ansible_env.HOME }}/.zshrc"
      register: zshrc_contents
      ignore_errors: true
      changed_when: false
      when: ansible_os_family == "Darwin" and is_ci | bool
