- name: Apt Packages
  tags: apt_packages
  become: true
  block:
    - name: (Apt) Import legacy apt keys
      ansible.builtin.apt_key:
        url: "{{ legacy_apt_key.value.key }}"
      with_dict: "{{ repos }}"
      loop_control:
        loop_var: legacy_apt_key
        label: "{{ legacy_apt_key }}"
      when: legacy_apt_key.value.in_keyring
      check_mode: false

    - name: (Apt) Import apt keys
      ansible.builtin.get_url:
        url: "{{ apt_key.value.key }}"
        dest: "/etc/apt/trusted.gpg.d/{{ apt_key.value.key | basename }}"
        mode: "0644"
        force: true
      with_dict: "{{ repos }}"
      loop_control:
        loop_var: apt_key
        label: "{{ apt_key }}"
      when:
        - not apt_key.value.in_keyring
      check_mode: false

    - name: (Apt) Add apt repos
      ansible.builtin.apt_repository:
        repo: "{{ apt_repo.value.repository }}"
        filename: "{{ apt_repo.value.name }}"
        update_cache: false
      register: added_repos
      with_dict: "{{ repos }}"
      loop_control:
        loop_var: apt_repo
        label: "{{ apt_repo }}"
      check_mode: false

    - name: (Apt) Update apt cache
      ansible.builtin.apt:
        update_cache: true
      check_mode: false

    - name: (Apt) Upgrade Packages
      ansible.builtin.apt:
        upgrade: full
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    - name: (Apt) Install SFW apt packages
      ansible.builtin.apt:
        name: "{{ apt_sfw_p_item }}"
        state: present
      loop: "{{ sfw_apt_packages }}"
      loop_control:
        loop_var: apt_sfw_p_item
        label: "{{ apt_sfw_p_item }}"

    - name: (Apt) Install NSFW apt packages
      ansible.builtin.apt:
        name: "{{ apt_nsfw_p_item }}"
        state: present
      loop: "{{ nsfw_apt_packages }}"
      loop_control:
        loop_var: apt_nsfw_p_item
        label: "{{ apt_nsfw_p_item }}"
      when: nsfw_mode | bool
