---
- name: Install Fastfetch
  tags: install_fastfetch
  become: true
  block:
    - name: (Fastfetch) Install required packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - pkg-config
          - cmake
          - gcc
          - g++
        state: present
      check_mode: false

    - name: (Fastfetch) Clone repository
      ansible.builtin.git:
        repo: https://github.com/fastfetch-cli/fastfetch.git
        dest: /tmp/Fastfetch
        version: master

    - name: (Fastfetch) Check if Fastfetch is installed
      ansible.builtin.stat:
        path: /usr/local/bin/fastfetch
      register: fastfetch_installed

    - name: (Fastfetch) Build and Install Fastfetch if not present
      ansible.builtin.command: |
        mkdir -p /tmp/Fastfetch/build &&
        cd /tmp/Fastfetch/build &&
        cmake .. &&
        cmake --build . --target fastfetch --target flashfetch
      when: not fastfetch_installed.stat.exists

    - name: (Fastfetch) Clean up source
      ansible.builtin.file:
        path: /tmp/Fastfetch
        state: absent
      when: not fastfetch_installed.stat.exists
