---
- name: Sync Home
  tags: sync_home
  block:
    - name: (Sync Home) Find all files and directories
      ansible.builtin.find:
        paths: "{{ '/tmp/oj39/universal-setup/files/' ~ ansible_facts['os_family'] | lower ~ '/home' if pwd.stdout is match('^/tmp/.*') else 'files/' ~ ansible_facts['os_family'] | lower ~ '/home' }}"
        recurse: true
      register: find_result
      changed_when: false

    - name: (Sync Home) Create directories and symlinks
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ ansible_env.HOME }}/{{ item.path | regex_replace('^' ~ ('/tmp/oj39/universal-setup/files/' ~ ansible_facts['os_family'] | lower ~ '/home/' if pwd.stdout is match('^/tmp/.*') else 'files/' ~ ansible_facts['os_family'] | lower ~ '/home/'), '') }}"
        state: "{{ 'directory' if item.isdir else 'link' }}"
        force: "{{ not item.isdir }}"
      loop: "{{ find_result.files }}"
      loop_control:
        label: "{{ item.path }}"
      when: pwd.stdout is not match("^/tmp/.*")

    - name: (Sync Home) Synchronize files
      ansible.posix.synchronize:
        src: "/tmp/oj39/universal-setup/files/{{ ansible_facts['os_family'] | lower }}/home/"
        dest: "{{ ansible_env.HOME }}/"
      when: pwd.stdout is match("^/tmp/.*")
