---
- name: Sync Home
  tags: sync_home
  block:
    - name: (Sync Home) Find all files in the source directory
      ansible.builtin.find:
        paths: "{{ '/tmp/oj39/universal-setup/files/' ~ ansible_facts['os_family'] ~ '/home' if pwd.stdout is match('^/tmp/.*') else 'files/' ~ ansible_facts['os_family'] ~ '/home' }}"
        recurse: true
        file_type: file
      register: files_to_link

    - name: (Sync Home) Create symbolic links for all files
      ansible.builtin.file:
        src: "{{ f_l_item.path }}"
        dest: "{{ ansible_env.HOME }}/{{ f_l_item.path | regex_replace('^files/' ~ ansible_facts['os_family'] ~ '/home/', '') }}"
        state: link
        force: true
        follow: false
      loop: "{{ files_to_link.files }}"
      loop_control:
        loop_var: f_l_item
        label: "{{ f_l_item.path }}"
      when: pwd.stdout is not match("^/tmp/.*")

    - name: (Sync Home) Synchronize files
      ansible.posix.synchronize:
        src: "/tmp/oj39/universal-setup/files/{{ ansible_facts['os_family'] }}/home/"
        dest: "{{ ansible_env.HOME }}/"
      when: pwd.stdout is match("^/tmp/.*")
