---
- name: Sync Home
  tags: sync_home
  block:
    - name: (Sync Home) Find all directories
      ansible.builtin.shell:
        cmd: >
          find {{ '/tmp/oj39/universal-setup/files/' ~ ansible_facts['os_family'] | lower ~ '/home' if pwd.stdout is match('^/tmp/.*') else 'files/' ~ ansible_facts['os_family'] | lower ~ '/home' }}
          -type d -printf '%P\n'
      register: find_dirs
      changed_when: false

    - name: (Sync Home) Create directories
      ansible.builtin.command:
        cmd: "mkdir -p {{ ansible_env.HOME }}/{{ item }}"
      loop: "{{ find_dirs.stdout_lines }}"
      when:
        - pwd.stdout is not match("^/tmp/.*")
        - item != ''
      changed_when: false

    - name: (Sync Home) Create symlinks
      ansible.builtin.shell:
        cmd: >
          find {{ '/tmp/oj39/universal-setup/files/' ~ ansible_facts['os_family'] | lower ~ '/home' if pwd.stdout is match('^/tmp/.*') else 'files/' ~ ansible_facts['os_family'] | lower ~ '/home' }}
          -type f -print0 | xargs -0 -I {} ln -sf {} {{ ansible_env.HOME }}/{/.}
      when: pwd.stdout is not match("^/tmp/.*")
      changed_when: false

    - name: (Sync Home) Synchronize files
      ansible.posix.synchronize:
        src: "/tmp/oj39/universal-setup/files/{{ ansible_facts['os_family'] | lower }}/home/"
        dest: "{{ ansible_env.HOME }}/"
      when: pwd.stdout is match("^/tmp/.*")
