name: Ansible Playbook CI Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint
      - name: Lint Ansible Playbook
        run: ansible-lint

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nsfw: [true, false]
    env:
      OJ39_ANSIBLE_INSTALL_NSFW: ${{ matrix.nsfw }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Run Ansible Playbook
        run: |
          ansible-playbook base_installation.yml --syntax-check
          ansible-playbook base_installation.yml --check -vvv

  integration-test:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nsfw: [true, false]
    env:
      OJ39_ANSIBLE_INSTALL_NSFW: ${{ matrix.nsfw }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Run Ansible Playbook
        run: |
          ansible-playbook base_installation.yml
