name: Ansible Playbook CI
## When testing with act, use: act --matrix os:ubuntu-latest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint
      - name: Lint Ansible Playbook
        run: ansible-lint

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Run Ansible Playbook
        run: |
          ansible-playbook base_installation.yml --syntax-check
          ansible-playbook base_installation.yml --check

  integration-test:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Run Ansible Playbook
        run: |
          ansible-playbook base_installation.yml
        #  run: |
        #  which nvim
        #  nvim --version
        #  which tmux
        #  tmux -V
      # - name: Verify Installation
